BIOINFO_ROOT: "/mnt/trcanmed/snaketree/"
PRJ_ROOT: "/mnt/trcanmed/snaketree/prj/pdx_multiomics_integration_preproc"
VERSION: "1"
DATA_DIR: "/local/share/data"
SRC: "../../local/src"
TEST_SIZE: .3
TARGET_COL: "Cetuximab Standard 3wks"
FULL_CLASS_LABELS:
  ["Objective Response or Stable Disease", "Progressive Disease (>35%)"]
CLASS_LABELS: ["OR+SD", "PD"]
CLASS_BINS: [35]
DIABLO_MINFEATURES: 4
DIABLO_MAXFEATURES: 10
DIABLO_STEP: 2
